UserGroup About details page
strandls/biodiv-ui pull request #22
Opened 2020-07-30 18:31 UTC by teamdraftbox

1.About page created with readonly capability
2.Admin Image List Component created in group/ common directory
3.Edit group button added in light nav page

2020-08-13 16:29 UTC, harshzalavadiya requested changes

2020-08-13 16:29 UTC, harshzalavadiya commented on src/components/@core/navigation-menu/light/left-menu/logo.tsx
> +      )}
Can you transfer this to seprate component and just import that

2020-08-13 16:29 UTC, harshzalavadiya commented on src/components/pages/group/about/index.tsx
> +      <MapDrawView coordinates={coordinates} title={t("GROUP.SPATIAL_COVERGE")} />
Instead of draw use <Previewer/> from `naksha-components-react`

2020-08-13 16:29 UTC, harshzalavadiya commented on src/components/pages/group/about/map-draw-view/index.tsx
> +import { Box, Heading } from "@chakra-ui/core";
This component can be discarded as <Previewer/> component will take over

2020-08-13 16:29 UTC, harshzalavadiya commented on src/pages/group/[groupName]/about.tsx
> +      moderators: data.moderatorList.map(({ name: label, id: value, ...others }) => ({
```suggestion
  const { success: s1, data: groupInfo } = await axGetGroupEditInfoByGroupId(currentGroup.id, ctx);
  const { success: s2, data } = await axGetGroupAdministratorsByGroupId(currentGroup.id, ctx);
  if (s1 && s2) {
    return {
      habitats: habitatList,
      speciesGroups,
      // You can just override key by just checking for condition
      // Preferablly let it be blank and use default where icon property is used
      groupInfo: { ...groupInfo, icon: icon || "default" },
      userGroupId: currentGroup.id,
      // There's no need of over destructuring here
      founders: data.founderList.map((o) => ({
        ...o,
        name: label,
        id: value,
      })),
      moderators: data.moderatorList.map(({ name: label, id: value, ...others }) => ({
```

2020-08-18 14:51 UTC, closed without merging

2020-08-18 14:52 UTC, teamdraftbox commented
Closed as new branch with the above feature and latest changes from master has been created