Customfield edit
strandls/biodiv-ui pull request #230
Opened 2022-06-30 10:29 UTC by arunasd463

1) Added an Update feature for custom fields with pre populated form.
2) Feature upgrade on add custom field form

2022-07-01 08:14 UTC, harshzalavadiya requested changes
@arunasd463  please go through code suggestions and make necessary changes

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/image-uploader-field/image-card.tsx
> +      {disabled?null:
this can be simplified into `{!disabled && <Closebutton/>}`

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/image-uploader-field/index.tsx
> +      ) : disabled ? "Image not available" :(
Please translate this field

2022-07-01 08:14 UTC, harshzalavadiya commented on src/services/usergroup.service.ts
> +};
missing empty line at end of file please add that as well + run it through formatter

2022-07-01 08:14 UTC, harshzalavadiya commented on locales/bn/group.json
> +    },
This keys don't match with `en` at all and there's capitalised key string as well, just use i18nAlly extension to translate each field and remove the ones that you are not using

2022-07-01 08:14 UTC, harshzalavadiya commented on locales/fr/group.json
> +    },
I think same thing for all languages

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +      })
please create common file that shares the duplicate validation schema with original `src/components/pages/group/common/custom-field/custom-field-form.tsx`, we should try to avoid duplicates like this which can easily go out of sync when internal schema changes

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +      return acc;
if possible move this to common file as well since this logic is reused as well

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +    console.warn(defaultValues)
remove this since console.warn isn't appropriate here

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +      hForm.reset(defaultValues);
also if possible instead of resetting form just unload whole form so it can be freshly loaded everytime

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +          <Box gridColumn="1/4">
please use <GridItem/> component instead of `gridColumn` props https://chakra-ui.com/docs/components/grid#spanning-columns

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +            disabled={false}
`disabled={false}` is redundant

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +            <TextAreaField name="notes" disabled={false} label={t("form:notes")} />
`disabled={false}` is redundant here as well

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +}
missing empty line at end of file

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-table/custom-field-row.tsx
> +
too many empty lines

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-table/index.tsx
> +    {setIsEdit(true)}
`{setIsEdit(true)}` is same as `setIsEdit(true)`

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-table/index.tsx
> +    setEditCustomFieldData(customFields.filter(({ customFields: { id } }) => id == index))
avoid unnecessary destructuring it makes hard to understand

```diff
- setEditCustomFieldData(customFields.filter(({ customFields: { id } }) => id == index))
+ setEditCustomFieldData(customFields.filter((cfData) => cfData.customFields.id == index))
```

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/index.tsx
> +          )
this blocks can be easily reversed and we can change `!isEdit` to `isEdit`, also if possible please simply both turnary conditions

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/options-field.tsx
> +                  //  name={`values.${index}.value`}
please remove comments from code before pushing it

2022-07-01 08:14 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/options-field.tsx
>                <Box gridColumn="1/4">
move `gridColumn` to <GridItem/> Component + `colspan` prop

2022-07-04 11:38 UTC, arunasd463 commented
1) Added an Update feature for custom fields with pre-populated form.
2) Feature upgrade on add custom field form

2022-07-04 12:01 UTC, harshzalavadiya commented on src/components/pages/group/common/custom-field/custom-field-edit-from.tsx
> +      return acc;
this is still the same thing

2022-07-05 14:12 UTC, harshzalavadiya approved these changes

2022-07-05 14:13 UTC, merged